package constants

const HTTP_REQUEST_TIMEOUT_MS_NAME = "HTTP_REQUEST_TIMEOUT_MS"
const DATABASE_TIMEOUT_MS_NAME = "DATABASE_TIMEOUT_MS"
const HTTP_CLIENT_REQUEST_TIMEOUT_MS_NAME = "HTTP_CLIENT_REQUEST_TIMEOUT_MS"
